const API_URL = "https://script.google.com/macros/s/AKfycbxw8Ada1H_P5IZaTXlZXUI9RGgmmYiDv1zBoeeDc-qGdkt29Db4jg-CMRdNX2gKPi4n/exec"; // Pegá aquí la URL /exec de tu Web App de Apps Script al publicar.
const seedQuestions = [
  {id:"q1",game:"Detective de palabras",question:"Al referirnos a un espacio físico adaptado, ¿qué expresión es la más adecuada?",options:["Baño para discapacitados","Baño para capacidades especiales","Baño accesible","Baño para lisiados"],answer:2,explanation:"“Baño accesible” describe la característica del espacio sin definir a las personas."},
  {id:"q2",game:"Detective de palabras",question:"¿Cuál es el error principal en la frase “Mi compañero sufre de autismo”?",options:["No usar el nombre del compañero","No usar el término especial","El término autismo es incorrecto","El uso del verbo sufrir"],answer:3,explanation:"El verbo “sufrir” condiciona la discapacidad como si fuera sinónimo de padecimiento."},
  {id:"q3",game:"Detective de palabras",question:"En el contexto de la visión, ¿cuál de estas opciones es preferible?",options:["El corto de vista","El no vidente/invidente","Persona ciega","2 y 3 son correctas"],answer:2,explanation:"“Persona ciega” antepone a la persona sin invisibilizar su condición."},
  {id:"q4",game:"Detective de palabras",question:"Según el principio de Persona Primero, ¿cuál es la forma correcta?",options:["Persona con discapacidad","Discapacitado","Persona especial","Persona con capacidades diferentes"],answer:0,explanation:"“Persona con discapacidad” antepone a la persona y es consistente con los estándares de derechos humanos."},
  {id:"q5",game:"Detective de palabras",question:"¿Por qué “capacidades diferentes” es un término innecesario?",options:["Es muy largo","Es demasiado formal","Solo aplica a niños","Invisibiliza la discapacidad"],answer:3,explanation:"Puede invisibilizar la discapacidad y convertir a la persona en un supuesto “superhéroe”."},
  {id:"q6",game:"Detective de palabras",question:"Si una persona no tiene discapacidad, el término correcto es:",options:["Persona normal","Persona sana","Persona sin discapacidad","Persona completa"],answer:2,explanation:"Los otros términos asocian la discapacidad con enfermedad, falta o anormalidad."},
  {id:"q7",game:"Detective de palabras",question:"¿Cuál de estas frases usa un lenguaje preciso y no estigmatizante?",options:["Hay que ayudar a los discapacitados de la organización.","Viene una persona no vidente a atenderse.","El normal de la oficina técnica ya llegó.","Se debe aclarar en la ficha que el paciente tiene Autismo."],answer:3,explanation:"La frase es precisa y evita términos estigmatizantes o victimizantes."}
];
let questions = seedQuestions, leaders = [{alias:"PlanetaAccesible",points:320},{alias:"IncluirEsHoy",points:280},{alias:"PalabrasAbren",points:250}], current=0, responses=[];
const $=(s)=>document.querySelector(s); const $$=(s)=>[...document.querySelectorAll(s)];
function renderBoard(){const list=$("#leaderboard-list");list.innerHTML=leaders.slice(0,10).map((x,i)=>`<li><span class="rank">${i+1}</span><span class="alias">${escapeHtml(x.alias)}</span><span class="points">${x.points} puntos</span></li>`).join("")}
function escapeHtml(text){const d=document.createElement("div");d.textContent=text;return d.innerHTML}
async function loadData(){if(!API_URL){$("#connection-state").textContent="Modo demostración";renderBoard();return}try{const r=await fetch(`${API_URL}?action=bootstrap`,{cache:"no-store"});const data=await r.json();questions=data.questions?.length?data.questions:seedQuestions;leaders=data.leaderboard||[];$("#connection-state").textContent="Tablero actualizado";renderBoard()}catch{ $("#connection-state").textContent="Mostrando datos locales";renderBoard()}}
function beginQuiz(){current=0;responses=[];$("#quiz").hidden=false;$("#quiz").scrollIntoView({behavior:"smooth",block:"start"});renderQuestion()}
function renderQuestion(){const q=questions[current];$("#quiz-progress").textContent=`${current+1} / ${questions.length}`;$("#progress-fill").style.width=`${((current+1)/questions.length)*100}%`;$("#question-game").textContent=q.game||"Detective de palabras";$("#question-text").textContent=q.question;$("#feedback").hidden=true;$("#answers").innerHTML="";q.options.forEach((o,i)=>{const b=document.createElement("button");b.className="answer";b.textContent=o;b.addEventListener("click",()=>answer(i));$("#answers").append(b)})}
function answer(selected){const q=questions[current],buttons=$$(".answer");buttons.forEach((b,i)=>{b.disabled=true;if(i===q.answer)b.classList.add("correct");else if(i===selected)b.classList.add("incorrect")});responses.push({id:q.id,selected});const right=selected===q.answer;const feedback=$("#feedback");feedback.innerHTML=`<h3>${right?"Una palabra abre puertas":"Sigamos aprendiendo"}</h3><p>${q.explanation}</p><button class="button ${right?"button-primary":""}" id="next-question">${current===questions.length-1?"Ver mi resultado":"Continuar"} <span aria-hidden="true">→</span></button>`;feedback.hidden=false;$("#next-question").addEventListener("click",()=>{current++;current<questions.length?renderQuestion():completeQuiz()})}
function completeQuiz(){const score=responses.reduce((n,r,i)=>n+(r.selected===questions[i].answer?100:0),0);$("#quiz").hidden=true;sessionStorage.setItem("didPendingScore",String(score));$("#alias-dialog").showModal()}
async function submitScore(alias){const score=Number(sessionStorage.getItem("didPendingScore")||0);let result={alias,points:score};if(API_URL){try{const r=await fetch(API_URL,{method:"POST",headers:{"Content-Type":"text/plain;charset=utf-8"},body:JSON.stringify({action:"submit",alias,responses,clientId:getClientId()})});result=await r.json()}catch{toast("No pudimos guardar tu puntaje. Intentá nuevamente.");return}}leaders=[...leaders,result].sort((a,b)=>b.points-a.points);renderBoard();$("#tablero").scrollIntoView({behavior:"smooth"});toast(`¡Misión completada! Sumaste ${result.points} puntos.`);sessionStorage.removeItem("didPendingScore")}
function getClientId(){let id=localStorage.getItem("didClientId");if(!id){id=crypto.randomUUID();localStorage.setItem("didClientId",id)}return id}function toast(message){const t=$("#toast");t.textContent=message;t.hidden=false;setTimeout(()=>t.hidden=true,3500)}
$$(".start-quiz").forEach(b=>b.addEventListener("click",beginQuiz));$(".exit-quiz").addEventListener("click",()=>$("#quiz").hidden=true);$(".puzzle-button").addEventListener("click",()=>toast("Este rompecabezas estará disponible en una próxima misión."));$("#alias-form").addEventListener("submit",e=>{e.preventDefault();const a=$("#alias").value.trim();if(a.length<3)return;$("#alias-dialog").close();submitScore(a)});loadData();
